spring:
  application:
    name: music-metadata-service
  sql:
    init:
      mode: always
      schema-locations: classpath:ice_schema.sql
  datasource:
    url: ${DB_URL:jdbc:h2:mem:musicdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE}
    driver-class-name: org.h2.Driver
    username: ${DB_USER:sa}
    password: ${DB_PWD:}
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
