-- schema.sql copied from ice_schema.sql so Spring Boot will execute at startup/tests
CREATE TABLE IF NOT EXISTS artist_profiles (
    artist_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    artist_name VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    artist_of_the_day_marker BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE INDEX IF NOT EXISTS idx_artist_profiles_artist_name ON artist_profiles (artist_name);

CREATE TABLE IF NOT EXISTS artist_tracks (
    track_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    artist_id BIGINT NOT NULL,
    title VARCHAR(255) NOT NULL,
    genre VARCHAR(100),
    length INT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_artist_profiles FOREIGN KEY (artist_id) REFERENCES artist_profiles(artist_id)
);

CREATE INDEX IF NOT EXISTS idx_artist_tracks_artist_id ON artist_tracks (artist_id);

CREATE TABLE IF NOT EXISTS artist_aliases (
    alias_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    artist_id BIGINT NOT NULL,
    alias_name VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_artist_aliases_artist FOREIGN KEY (artist_id) REFERENCES artist_profiles(artist_id)
);

CREATE INDEX IF NOT EXISTS idx_artist_aliases_artist_id ON artist_aliases (artist_id);
